name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: miri, clippy, fmt
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo miri test --verbose
    - name: Clippy
      run: cargo clippy
    - name: Fmt
      run: cargo fmt --check
